[metadata]
# This includes the license file(s) in the wheel.
# https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
name = photologue
decription = Cleans up duplicates from photo libraries
author = Matthew Anderson
license = None
license_files = LICENSE
platforms = osx
classifers =
  Programming Language :: Python :: 3.14

[options]
packages = photologue
install_requires =
  PyYAML>=6.0.3
  configparser==5.3.0
  docopt==0.6.2
  types-PyYAML>=6.0.3
  types-docopt==0.6.11
python_requires = >=3.14
package_dir =
  =src
zip_safe = no

[options.extras_require]
testing =
  flake8
  mypy
  pytest
  pytest-cov
  snakeviz
  tox

[options.package_data]
catalouge = py.typed

[flake8]
max-line-length = 160
